name: peceras_app_funcional_completo
description: App funcional completa de gestión de peceras.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logging: ^1.0.0
  excel: ^2.0.4   # Para manejar archivos Excel
  path_provider: ^2.0.2  # Para obtener las rutas de almacenamiento
  open_file: ^3.0.3      # Para abrir los archivos
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.2.0
  fetch_client: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/fondo_pecera.jpg
